### ISSUE TITLE
Error when selecting more than 6 clusters regardless of data

### ISSUE THREAD

**Issue by ndell** [zdealveindy/twinspanR#1]
I've encountered a strange error with the newer version of twinspanR when running modified TWINSPAN. When selecting a higher number of clusters than 6 (or 8 when using my home computer), regardless of the data I am using, I get this error:

Error in order(cluster.heter, decreasing = T) : 
  R_Reprotect: only 4 protected items, can't reprotect index -1

This seems somewhat cryptic to me, but having modified the code to print out objects to exactly where it stopped, I believe the issue arises at line 130 or 142 of "twinspan.r", depending on whether i is the last group or not. 

If I use twinspanR v0.16 on R 3.4.4, the following code will supply a result. If I use twinspanR v0.22 on R 4.1.1, it will stop with the above error message. 

data(danube)
twinspan(danube$spe, modif=T, clusters=7). 

I wonder if this is some problem with having had to switch over from package rioja to package riojaExtra? It had been quite some time since I had used modified TWINSPAN for anything, so I am unsure if the issue arose between those versions of this package and R, respectively. 

I suppose my solution for now is to use the old versions of R, rioja, and twinspanR to implement modified TWINSPAN as needed. Has this been brought to your attention before?

**Comment by zdealveindy** [comment]
In the latest version of twinspanR, the clustering works as it should. There has been a multiple changes done in the code, so I am not sure which of them fixed it, but good that it works :)
